language: cpp

notifications:
  slack: sriformalmethods:wSnZggI8D3mxI5uqDsElZbV2
  
sudo: true

compiler:
  # - clang (Disabling until boost and clang play well)
  - gcc
  
env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug 
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=ON

addons:
  apt:
    update: true
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - flex
      - g++-5
      - libgmp-dev
      - libboost-program-options1.55-dev 
      - libboost-iostreams1.55-dev
      - libboost-test1.55-dev
      - libboost-thread1.55-dev
      - libboost-system1.55-dev
      - libreadline-dev
      - default-jre
      - gperf
      - zlib1g-dev
      - g++-5

before_install:
  - CC=gcc-5 && CXX=g++-5
    
install:
  - bash contrib/install_yices2.sh
  - bash contrib/install_opensmt2.sh
  - if [[ $ENABLE_COVERAGE == ON ]]; then 
      pip install --user cpp-coveralls;
    fi
  
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DENABLE_COVERAGE=${ENABLE_COVERAGE} ..
  - make 
  - make check

after_script:
  - if [[ $ENABLE_COVERAGE == ON ]]; then
      coveralls -r .. -b . --gcov-options '\-lp';
    fi
  
notifications:
  slack: sallydevelopers:0ShJwlN0m6sOFGb5wfaJcLAB
