language: cpp

sudo: false

compiler:
  # - clang (Disabling until boost and clang play well)
  - gcc
  
env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug 
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=ON

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libgmp-dev
      - libboost-program-options1.55-dev 
      - libboost-iostreams1.55-dev
      - libboost-test1.55-dev
      - libboost-thread1.55-dev
      - libboost-system1.55-dev
      - default-jre
      - gperf

cache:
  directories:
    - $HOME/yices2

install:
  - bash contrib/install_yices2.sh
  - if [[ $ENABLE_COVERAGE == ON ]]; then 
      sudo pip install cpp-coveralls;
    fi
  
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DENABLE_COVERAGE=${ENABLE_COVERAGE} -DYICES2_HOME=$HOME/yices2 ..
  - make 
  - make check

after_script:
  - if [[ $ENABLE_COVERAGE == ON ]]; then
      coveralls -r .. -b . --gcov-options '\-lp';
    fi
  
